apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: student11
  name: student11-deployment
spec:
  selector:
    matchLabels:
      app: student11
  template:
    metadata:
      labels:
        app: student11
    spec:
      containers:
      - name: student11
        image: registry.tanzu.dk/ops2devops/student11:v1
