apiVersion: apps/v1
kind: Deployment
metadata:
  name: student11-deployment
  namespace: student11
spec:
  selector:
    matchLabels:
      app: student11
  template:
    metadata:
      labels:
        app: student11
    spec:
      containers:
      - name: student11
        image: registry.tanzu.dk/ops2devops/student11:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student11
spec:
  type: NodePort
  selector:
    app: student11
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30021 # Remember to change to student number.

